travis:
  secure:
    BINSTAR_TOKEN: baXZ/b7NKbBGV/Zp9Qg2czPHV0BGpNNxBr3WDpG1bBOjShJBYQ3h6MX7DN7B1kZsTos7Qs1ld5zCyHINhXpG5Gw7diZqSzX1EFVkTi/XFdLNFdiPAUZzSpyI85VrNHmGgnaSq/FTwFusdDlpBcae3w3MaDc3ItyxaDSYqJLuLzFNSY1NjszCX0Erh/httF8oH/P510F+HzchnKUm5NzAGC/DooV2lYS9H185iWoTDJDGflRqgk++o8cQ6nV5qWKlWewCFQOd6GLF/H/nRq+VUVeIz7cY4ZiETgE5c+h9X8LmLQOVj+AwG+5EOE7xOY5Pt8Bem8PepTa8Fi3tVkvCGKoqekuJ75dg8iqZVjImAxl8XnhwRYoKaUS3TCb7dbqOEOkDj5MXBR2jAiIsnqhsYmCNUzgAqoko/GGNoJvhaNharNG2YjuE9YaKA+6tcZ3/bnsdMp8GeHZjseGVOLXmSZryD/oxzrpp/PXGa6QcIENNlmoyyXQjxzsGgbQzW8nWTXL3gqlfEy5sTRlpu+BD+38RL5X91MYL3mqbyaug1l3afl5XD2TcMbA9+ZZ69b2cLtfeF3hPbDJzummEeMCac86XX908jnHx8WnCxNwS7Xv9bvI80HrWdRRtog6jKICCjD+7xoDcihsgsHd0BvjWmKvOXowEZ4B3I0P+0Nz7Ks4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
